CREATE TABLE [dbo].[TB_ATTENDANCE_LIST]
(
	[WORSHIP_ID] CHAR(14) NOT NULL , 
	[MEMBER_ID] NVARCHAR(450) NOT NULL, 
	[ATTENDANCE_TYPE] VARCHAR(30) NOT NULL, 
	[REGISTER_DT] DATETIME NOT NULL, 	
    [ESTIMATED_ARRIVAL] TIME NULL, 
    [SIGN_AGREEMENT] BIT NULL, 
    [INITIAL] VARCHAR(20) NULL, 
	[DESCR] NVARCHAR(300) NULL, 
	[SIGN_IMG] IMAGE NULL,     
    CONSTRAINT [PK_TB_ATTENDANCE_LIST] PRIMARY KEY ([WORSHIP_ID], [MEMBER_ID])
)
