CREATE TABLE [dbo].[TB_CATEGORY_MST]
(
	[CATEGORY_ID] VARCHAR(30) NOT NULL , 
    [CATEGORY_DESCR] NVARCHAR(50) NOT NULL, 
    [ACTIVE_YN] CHAR NULL, 
    [ABBR_CD] CHAR(2) NULL, 
    [CREATE_DT] DATE NOT NULL, 
    CONSTRAINT [PK_TB_CATEGORY_MST] PRIMARY KEY ([CATEGORY_ID]) 
)
