CREATE TABLE [dbo].[TB_CODE_MST]
(
	[CODE_ID] CHAR(4) NOT NULL , 
    [CATEGORY_ID] VARCHAR(30) NOT NULL, 
    [CODE_DESCR] NVARCHAR(450) NOT NULL, 
    [SORT_ORDER] INT NULL, 
    [ACTIVE_YN] CHAR NULL, 
    [CREATE_DT] DATETIME NOT NULL, 
    PRIMARY KEY ([CODE_ID], [CATEGORY_ID])
)
