CREATE TABLE [dbo].[TB_MEMBER_INFO]
(
	[MEMBER_ID] CHAR(10) NOT NULL PRIMARY KEY, 
    [REGISTER_DATE] DATE NOT NULL, 
    [FIRST_NAME] VARCHAR(30) NOT NULL, 
    [LAST_NAME] VARCHAR(20) NULL, 
    [EMAIL_ADDR] VARCHAR(50) NULL, 
    [BIRTH_DATE] DATE NULL, 
    [PHONE_NUM] VARCHAR(20) NULL,     
    [FAMILY_ID] CHAR(5) NULL, 
    [GROUP_CD] CHAR(4) NULL, 
    [TEAM_CD] CHAR(4) NULL,
    [PHOTO_IMG] IMAGE NULL, 
    [SIGN_IMG] IMAGE NULL
)
