CREATE TABLE [dbo].[TB_WORSHIP_INFO]
(
	[WORSHIP_ID] CHAR(14) NOT NULL PRIMARY KEY, 
    [WORSHIP_DATE] DATETIME NOT NULL, 
    [WORSHIP_TYPE] CHAR(4) NULL,     
    [WORSHIP_LOCATION] VARCHAR(200) NULL, 
    [DESCRIPTION] VARCHAR(250) NULL
    
)
