CREATE PROCEDURE [dbo].[SP_DELETE_CATEGORY_MST]
	@categoryId varchar(30)
AS
BEGIN
	DELETE FROM TB_CATEGORY_MST
	      WHERE CATEGORY_ID = @categoryId;

    DELETE FROM TB_ID_MAPPING_MST
	 WHERE KEY_COLUMN = 'CATEGORY_ID'
	   AND KEY_VALUE = @categoryId;
END
