CREATE PROCEDURE [dbo].[SP_SEARCH_CODE_MST]
	@categoryId varchar(30)
AS
BEGIN
	SELECT 
			CODE_ID
		   ,CD.CATEGORY_ID
		   ,CODE_DESCR
		   ,SORT_ORDER
		   ,CD.ACTIVE_YN
		   ,CD.CREATE_DT
		   ,CT.CATEGORY_DESCR
	  FROM TB_CODE_MST   CD
	  JOIN TB_CATEGORY_MST   CT
	    ON CD.CATEGORY_ID = CT.CATEGORY_ID
	 WHERE CD.CATEGORY_ID = ISNULL(@categoryId, CD.CATEGORY_ID)
END
