CREATE PROCEDURE [dbo].[SP_SEARCH_CATEGORY_MST]
	@categoryId varchar(30)
AS
BEGIN
	SELECT 
			CATEGORY_ID
		   ,CATEGORY_DESCR
		   ,ACTIVE_YN
		   ,ABBR_CD
		   ,CREATE_DT
	  FROM TB_CATEGORY_MST
	 WHERE CATEGORY_ID = ISNULL(@categoryId, CATEGORY_ID)
END